# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake3

# The command to remove a file.
RM = /usr/bin/cmake3 -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /grad/mrahbardar/Aperture4

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /grad/mrahbardar/Aperture4

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@echo "Running CMake to regenerate build system..."
	/usr/bin/cmake3 --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@echo "Running CMake cache editor..."
	/usr/bin/ccmake3 -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /grad/mrahbardar/Aperture4/CMakeFiles /grad/mrahbardar/Aperture4/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /grad/mrahbardar/Aperture4/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named fmt

# Build rule for target.
fmt: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fmt
.PHONY : fmt

# fast build rule for target.
fmt/fast:
	$(MAKE) $(MAKESILENT) -f deps/fmt/CMakeFiles/fmt.dir/build.make deps/fmt/CMakeFiles/fmt.dir/build
.PHONY : fmt/fast

#=============================================================================
# Target rules for targets named Catch2WithMain

# Build rule for target.
Catch2WithMain: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Catch2WithMain
.PHONY : Catch2WithMain

# fast build rule for target.
Catch2WithMain/fast:
	$(MAKE) $(MAKESILENT) -f deps/catch/src/CMakeFiles/Catch2WithMain.dir/build.make deps/catch/src/CMakeFiles/Catch2WithMain.dir/build
.PHONY : Catch2WithMain/fast

#=============================================================================
# Target rules for targets named Catch2

# Build rule for target.
Catch2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Catch2
.PHONY : Catch2

# fast build rule for target.
Catch2/fast:
	$(MAKE) $(MAKESILENT) -f deps/catch/src/CMakeFiles/Catch2.dir/build.make deps/catch/src/CMakeFiles/Catch2.dir/build
.PHONY : Catch2/fast

#=============================================================================
# Target rules for targets named Aperture

# Build rule for target.
Aperture: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Aperture
.PHONY : Aperture

# fast build rule for target.
Aperture/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/Aperture.dir/build.make src/CMakeFiles/Aperture.dir/build
.PHONY : Aperture/fast

#=============================================================================
# Target rules for targets named problems

# Build rule for target.
problems: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 problems
.PHONY : problems

# fast build rule for target.
problems/fast:
	$(MAKE) $(MAKESILENT) -f problems/CMakeFiles/problems.dir/build.make problems/CMakeFiles/problems.dir/build
.PHONY : problems/fast

#=============================================================================
# Target rules for targets named em_wave

# Build rule for target.
em_wave: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 em_wave
.PHONY : em_wave

# fast build rule for target.
em_wave/fast:
	$(MAKE) $(MAKESILENT) -f problems/examples/src/CMakeFiles/em_wave.dir/build.make problems/examples/src/CMakeFiles/em_wave.dir/build
.PHONY : em_wave/fast

#=============================================================================
# Target rules for targets named test_particle

# Build rule for target.
test_particle: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_particle
.PHONY : test_particle

# fast build rule for target.
test_particle/fast:
	$(MAKE) $(MAKESILENT) -f problems/examples/src/CMakeFiles/test_particle.dir/build.make problems/examples/src/CMakeFiles/test_particle.dir/build
.PHONY : test_particle/fast

#=============================================================================
# Target rules for targets named sph_wave_vacuum

# Build rule for target.
sph_wave_vacuum: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sph_wave_vacuum
.PHONY : sph_wave_vacuum

# fast build rule for target.
sph_wave_vacuum/fast:
	$(MAKE) $(MAKESILENT) -f problems/sph_wave_test/src/CMakeFiles/sph_wave_vacuum.dir/build.make problems/sph_wave_test/src/CMakeFiles/sph_wave_vacuum.dir/build
.PHONY : sph_wave_vacuum/fast

#=============================================================================
# Target rules for targets named gca_test

# Build rule for target.
gca_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gca_test
.PHONY : gca_test

# fast build rule for target.
gca_test/fast:
	$(MAKE) $(MAKESILENT) -f problems/debug/src/CMakeFiles/gca_test.dir/build.make problems/debug/src/CMakeFiles/gca_test.dir/build
.PHONY : gca_test/fast

#=============================================================================
# Target rules for targets named pml_test

# Build rule for target.
pml_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pml_test
.PHONY : pml_test

# fast build rule for target.
pml_test/fast:
	$(MAKE) $(MAKESILENT) -f problems/debug/src/CMakeFiles/pml_test.dir/build.make problems/debug/src/CMakeFiles/pml_test.dir/build
.PHONY : pml_test/fast

#=============================================================================
# Target rules for targets named single_stream

# Build rule for target.
single_stream: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 single_stream
.PHONY : single_stream

# fast build rule for target.
single_stream/fast:
	$(MAKE) $(MAKESILENT) -f problems/two_stream/src/CMakeFiles/single_stream.dir/build.make problems/two_stream/src/CMakeFiles/single_stream.dir/build
.PHONY : single_stream/fast

#=============================================================================
# Target rules for targets named two_stream_1d

# Build rule for target.
two_stream_1d: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 two_stream_1d
.PHONY : two_stream_1d

# fast build rule for target.
two_stream_1d/fast:
	$(MAKE) $(MAKESILENT) -f problems/two_stream/src/CMakeFiles/two_stream_1d.dir/build.make problems/two_stream/src/CMakeFiles/two_stream_1d.dir/build
.PHONY : two_stream_1d/fast

#=============================================================================
# Target rules for targets named two_stream

# Build rule for target.
two_stream: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 two_stream
.PHONY : two_stream

# fast build rule for target.
two_stream/fast:
	$(MAKE) $(MAKESILENT) -f problems/two_stream/src/CMakeFiles/two_stream.dir/build.make problems/two_stream/src/CMakeFiles/two_stream.dir/build
.PHONY : two_stream/fast

#=============================================================================
# Target rules for targets named cooling_3d

# Build rule for target.
cooling_3d: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cooling_3d
.PHONY : cooling_3d

# fast build rule for target.
cooling_3d/fast:
	$(MAKE) $(MAKESILENT) -f problems/reconnection/src/CMakeFiles/cooling_3d.dir/build.make problems/reconnection/src/CMakeFiles/cooling_3d.dir/build
.PHONY : cooling_3d/fast

#=============================================================================
# Target rules for targets named cooling

# Build rule for target.
cooling: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cooling
.PHONY : cooling

# fast build rule for target.
cooling/fast:
	$(MAKE) $(MAKESILENT) -f problems/reconnection/src/CMakeFiles/cooling.dir/build.make problems/reconnection/src/CMakeFiles/cooling.dir/build
.PHONY : cooling/fast

#=============================================================================
# Target rules for targets named no_cooling

# Build rule for target.
no_cooling: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 no_cooling
.PHONY : no_cooling

# fast build rule for target.
no_cooling/fast:
	$(MAKE) $(MAKESILENT) -f problems/reconnection/src/CMakeFiles/no_cooling.dir/build.make problems/reconnection/src/CMakeFiles/no_cooling.dir/build
.PHONY : no_cooling/fast

#=============================================================================
# Target rules for targets named reconnection

# Build rule for target.
reconnection: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 reconnection
.PHONY : reconnection

# fast build rule for target.
reconnection/fast:
	$(MAKE) $(MAKESILENT) -f problems/reconnection/src/CMakeFiles/reconnection.dir/build.make problems/reconnection/src/CMakeFiles/reconnection.dir/build
.PHONY : reconnection/fast

#=============================================================================
# Target rules for targets named gr_single_ptc

# Build rule for target.
gr_single_ptc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gr_single_ptc
.PHONY : gr_single_ptc

# fast build rule for target.
gr_single_ptc/fast:
	$(MAKE) $(MAKESILENT) -f problems/gr_2d_kerr_schild/src/CMakeFiles/gr_single_ptc.dir/build.make problems/gr_2d_kerr_schild/src/CMakeFiles/gr_single_ptc.dir/build
.PHONY : gr_single_ptc/fast

#=============================================================================
# Target rules for targets named vacuum_wald

# Build rule for target.
vacuum_wald: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vacuum_wald
.PHONY : vacuum_wald

# fast build rule for target.
vacuum_wald/fast:
	$(MAKE) $(MAKESILENT) -f problems/gr_2d_kerr_schild/src/CMakeFiles/vacuum_wald.dir/build.make problems/gr_2d_kerr_schild/src/CMakeFiles/vacuum_wald.dir/build
.PHONY : vacuum_wald/fast

#=============================================================================
# Target rules for targets named grpic

# Build rule for target.
grpic: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 grpic
.PHONY : grpic

# fast build rule for target.
grpic/fast:
	$(MAKE) $(MAKESILENT) -f problems/gr_2d_kerr_schild/src/CMakeFiles/grpic.dir/build.make problems/gr_2d_kerr_schild/src/CMakeFiles/grpic.dir/build
.PHONY : grpic/fast

#=============================================================================
# Target rules for targets named gr_2d_kerr_schild

# Build rule for target.
gr_2d_kerr_schild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gr_2d_kerr_schild
.PHONY : gr_2d_kerr_schild

# fast build rule for target.
gr_2d_kerr_schild/fast:
	$(MAKE) $(MAKESILENT) -f problems/gr_2d_kerr_schild/src/CMakeFiles/gr_2d_kerr_schild.dir/build.make problems/gr_2d_kerr_schild/src/CMakeFiles/gr_2d_kerr_schild.dir/build
.PHONY : gr_2d_kerr_schild/fast

#=============================================================================
# Target rules for targets named magnetar

# Build rule for target.
magnetar: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 magnetar
.PHONY : magnetar

# fast build rule for target.
magnetar/fast:
	$(MAKE) $(MAKESILENT) -f problems/magnetar/src/CMakeFiles/magnetar.dir/build.make problems/magnetar/src/CMakeFiles/magnetar.dir/build
.PHONY : magnetar/fast

#=============================================================================
# Target rules for targets named parker

# Build rule for target.
parker: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 parker
.PHONY : parker

# fast build rule for target.
parker/fast:
	$(MAKE) $(MAKESILENT) -f problems/parker/src/CMakeFiles/parker.dir/build.make problems/parker/src/CMakeFiles/parker.dir/build
.PHONY : parker/fast

#=============================================================================
# Target rules for targets named test_sync_polarization

# Build rule for target.
test_sync_polarization: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_sync_polarization
.PHONY : test_sync_polarization

# fast build rule for target.
test_sync_polarization/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_sync_polarization.dir/build.make tests/CMakeFiles/test_sync_polarization.dir/build
.PHONY : test_sync_polarization/fast

#=============================================================================
# Target rules for targets named test_mpi2d

# Build rule for target.
test_mpi2d: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_mpi2d
.PHONY : test_mpi2d

# fast build rule for target.
test_mpi2d/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_mpi2d.dir/build.make tests/CMakeFiles/test_mpi2d.dir/build
.PHONY : test_mpi2d/fast

#=============================================================================
# Target rules for targets named test_exporter_mpi

# Build rule for target.
test_exporter_mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_exporter_mpi
.PHONY : test_exporter_mpi

# fast build rule for target.
test_exporter_mpi/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_exporter_mpi.dir/build.make tests/CMakeFiles/test_exporter_mpi.dir/build
.PHONY : test_exporter_mpi/fast

#=============================================================================
# Target rules for targets named test_exporter_snapshot

# Build rule for target.
test_exporter_snapshot: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_exporter_snapshot
.PHONY : test_exporter_snapshot

# fast build rule for target.
test_exporter_snapshot/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_exporter_snapshot.dir/build.make tests/CMakeFiles/test_exporter_snapshot.dir/build
.PHONY : test_exporter_snapshot/fast

#=============================================================================
# Target rules for targets named run_tests

# Build rule for target.
run_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_tests
.PHONY : run_tests

# fast build rule for target.
run_tests/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/run_tests.dir/build.make tests/CMakeFiles/run_tests.dir/build
.PHONY : run_tests/fast

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/tests.dir/build.make tests/CMakeFiles/tests.dir/build
.PHONY : tests/fast

#=============================================================================
# Target rules for targets named check

# Build rule for target.
check: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 check
.PHONY : check

# fast build rule for target.
check/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/check.dir/build.make tests/CMakeFiles/check.dir/build
.PHONY : check/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... check"
	@echo "... problems"
	@echo "... run_tests"
	@echo "... Aperture"
	@echo "... Catch2"
	@echo "... Catch2WithMain"
	@echo "... cooling"
	@echo "... cooling_3d"
	@echo "... em_wave"
	@echo "... fmt"
	@echo "... gca_test"
	@echo "... gr_2d_kerr_schild"
	@echo "... gr_single_ptc"
	@echo "... grpic"
	@echo "... magnetar"
	@echo "... no_cooling"
	@echo "... parker"
	@echo "... pml_test"
	@echo "... reconnection"
	@echo "... single_stream"
	@echo "... sph_wave_vacuum"
	@echo "... test_exporter_mpi"
	@echo "... test_exporter_snapshot"
	@echo "... test_mpi2d"
	@echo "... test_particle"
	@echo "... test_sync_polarization"
	@echo "... tests"
	@echo "... two_stream"
	@echo "... two_stream_1d"
	@echo "... vacuum_wald"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

