dt = 0.01
max_steps = 2000
subdivision_level = 5
N_r = 80
r_min = 1.0
r_max = 20.0
Bp = 1.0
Omega = 1.0
obliquity = 0.7854
damping_length = 15
damping_coef = 0.05
fld_output_interval = 20
output_dir = "Data_L5_sph"
sph_N_theta = 90
sph_N_phi = 180
