dt = 0.02
max_steps = 2000
subdivision_level = 4
N_r = 100
r_min = 1.0
r_max = 20.0
Bp = 1.0
Omega = 1.0
obliquity = 0.7854
damping_length = 20
damping_coef = 0.05
fld_output_interval = 200
output_dir = "Data_L4_dipole"
