#!/bin/bash
# Spherical-cavity TE/TM convergence sweep.
#
# For each subdivision level L in $LEVELS, generates a config_cavity_L${L}.toml
# with N_r and dt scaled with the angular resolution, runs cavity_resonator,
# and finally invokes cavity_analysis.py to produce the convergence plot.
#
# Scaling rationale (TE_{1,0,1}, r_min=1, r_max=5, T = 2π/k ≈ 6.7036):
#   - angular h ∝ 1/2^L (icosahedral subdivision)
#   - N_r       = 5 * 2^L         (matches dr ~ r_min * dθ; L=3 → N_r=40)
#   - dt        = 0.04 / 2^L      (CFL; L=3 → dt=0.005)
#   - max_steps = ceil(N_periods * T / dt)
#
# Override mode/time-span by exporting variables before invoking, e.g.
#   N_PERIODS=2 LEVELS="2 3 4" ./run_cavity_convergence.sh

set -e

LEVELS="${LEVELS:-${@:-2 3 4 5 6}}"
N_PERIODS="${N_PERIODS:-4}"

# Output downsampling stride. Stride=1 keeps every cochain (full
# output, current default); larger values keep every Nth global edge /
# face. Cuts disk usage and write time by ~N×; the L2 error on smooth
# fields is essentially unchanged. Default is 1 to preserve previous
# behavior; for L=6 sweeps you'll want 100–1000.
OUT_SUB="${OUT_SUB:-1}"

# Mode parameters (override via env)
MODE_L="${MODE_L:-1}"
MODE_M="${MODE_M:-0}"
MODE_N="${MODE_N:-1}"
MODE_POL="${MODE_POL:-E}"
TAG="${TAG:-${MODE_POL}${MODE_L}${MODE_M}n${MODE_N}}"

# Period for r_min=1, r_max=5; computed by Python on-the-fly so we don't
# have to hard-code it for every (l, m, n) combination.
PERIOD=$(python3 -c "
import sys; sys.path.insert(0,'.')
import cavity_analysis as ca, numpy as np
k = ca.cavity_eigenvalue($MODE_L, 1.0, 5.0, $MODE_N, '$MODE_POL')
print(f'{2*np.pi/k:.6f}')")
echo "=== Mode TE/TM ($MODE_POL) l=$MODE_L m=$MODE_M n_root=$MODE_N  T=$PERIOD ==="

DIRS=""
for L in $LEVELS; do
  NR=$((5 * (1 << L)))
  DT=$(awk -v L="$L" 'BEGIN { printf "%.10f", 0.04 / (2 ^ L) }')
  MAX_STEPS=$(awk -v T="$PERIOD" -v dt="$DT" -v np="$N_PERIODS" \
              'BEGIN { printf "%d", int(np*T/dt + 0.5) }')
  # Output every ~period/20 so we get ~80 snapshots over 4 periods.
  OUT_INT=$(awk -v ms="$MAX_STEPS" -v np="$N_PERIODS" \
            'BEGIN { n = int(ms / (np*20) + 0.5); if (n < 1) n = 1; print n }')

  DIR="Data_cavity_${TAG}_L${L}"
  CFG="config_cavity_${TAG}_L${L}.toml"
  DIRS="$DIRS $DIR"
  mkdir -p "$DIR"

  echo "=== L=$L  N_r=$NR  dt=$DT  max_steps=$MAX_STEPS  out_int=$OUT_INT ==="
  cat > "$CFG" << EOF
# Auto-generated by run_cavity_convergence.sh — L=$L  $TAG
dt = $DT
max_steps = $MAX_STEPS
subdivision_level = $L
N_r = $NR
r_min = 1.0
r_max = 5.0

mode_l = $MODE_L
mode_m = $MODE_M
mode_n_root = $MODE_N
mode_polarization = "$MODE_POL"
start_with_e = false
resonator_amp = 1.0

use_pec_bc = true
damping_length = 0
damping_coef = 0.0

fld_output_interval = $OUT_INT
fld_output_subsample = $OUT_SUB
output_dir = "$DIR"
sph_N_theta = 90
sph_N_phi = 180

Bp = 1.0
Omega = 0.0
obliquity = 0.0
EOF

  ./bin/cavity_resonator -c "$CFG"
  echo ""
done

echo "=== Convergence analysis ==="
python3 cavity_analysis.py $DIRS \
  --l $MODE_L --m $MODE_M --n_root $MODE_N --pol $MODE_POL \
  --convergence --b_half_shift \
  --target_samples 8000 --quad_order 3 \
  --plot "cavity_convergence_${TAG}.png" \
  --metric peak
