#!/usr/bin/env python3
"""Emit the Kerr-Wald convergence family: config_conv_L{3..6}_{ana,relax}.toml.

The point of the family is that every level differs ONLY in resolution:

  * r_min / r_max fixed and N_r doubling  ->  log-spaced shell radii are
    nested, so each level has a shell at exactly the same radius near the
    horizon (r = 1.1057) and at the reference radius (r = 8.016).  Without
    this the "horizon shell" radius moves with L and the measured flux ratio
    changes for reasons that have nothing to do with discretization error.
  * dt halves with h, so the Courant number is the same at every level.
  * damping_length doubles with N_r, so the absorbing sponge covers the same
    PHYSICAL radial range (r >= 9.33) at every level rather than a fixed
    number of layers.  It starts OUTSIDE the r = 8.016 reference shell, so the
    normalization is not pinned to the background by the damping.
  * damping_coef = 0.2, not the README's 0.08.  Scanned at L3: 0.08 leaves a
    4.8% ring still going at t = 110 M, 0.2 kills it to 0.09% by 150 M, and
    above ~0.5 the ramp itself starts reflecting and the ring grows again.
  * t_final = 220 M at every level, scored on the mean over 150-220 M.

Two configs per level:
  _ana   field_spin = bh_spin, 1 step   -> analytic on-shell state sampled on
                                           this mesh: the scoring target and
                                           the discrete-equilibrium residual.
  _relax field_spin = 0,  t = 220 M     -> the actual relaxation test.

Hodge axis (GRPIC_PLAN B1): each config pins use_whitney_hodge explicitly so
its meaning never depends on the code default.
  (plain)   use_whitney_hodge = false -> the diagonal-star baseline that
            produced the pre-B1 campaign data in Data_conv_L*_{ana,relax}.
            Both diagonal stars are O(1)-defective for a != 0; kept for A/B.
  _whitney  use_whitney_hodge = true  -> the Whitney Galerkin Hodge (B1b),
            output in Data_conv_L*_{ana,relax}_whitney so the baseline data
            is never clobbered.  The L3 ana run also dumps the assembled
            CSR operators (whitney.h5) for the python cross-check against
            hodge_lab_whitney.py.
"""
import os

LEVELS = [
    # L, N_r, dt,     damping_length, out_every_M
    (3,  22,  0.02,   6,              1),
    (4,  44,  0.01,   12,             1),
    (5,  88,  0.005,  24,             2),
    (6,  176, 0.0025, 48,             2),
]

# t = 220 M, scored on the mean over 150-220 M.  The relaxation rings with a
# ~18.5 M period (horizon <-> sponge cavity) that decays on ~33 M; at 60 M --
# the duration used for the original L3 measurement -- the ring is still 5-8%
# of the signal, i.e. two orders of magnitude above the quantity being
# measured.  By 150 M it is below 0.01%.
T_FINAL = 220.0
BH_SPIN = 0.998

HEADER = """\
# Kerr-Wald convergence family, level {L} -- {kind}
# Generated by make_conv_configs.py; edit that, not this.
#
# {desc}
"""

BODY = """
subdivision_level = {L}
N_r    = {N_r}
r_min  = 0.7
r_max  = 20.0
n_ghost_inner = 1
n_ghost_outer = 1

bh_spin         = {bh_spin}
field_spin      = {field_spin}
background_spin = {bh_spin}
B0              = 1.0
use_flat_metric = false

dt         = {dt}
max_steps  = {max_steps}
use_implicit = true
implicit_beta = 0.52
implicit_iters = 5
use_static_background = true

damping_length = {damping_length}
damping_coef   = 0.2

fld_output_interval = {out_interval}
output_dir          = "{output_dir}"

sph_N_theta = 90
sph_N_phi   = 180

update_d = true
update_b = true

# GRPIC_PLAN B1: constitutive Hodge map.  Pinned explicitly so the config
# means the same thing regardless of the solver's compiled-in default.
use_whitney_hodge = {use_whitney}{extra}
"""

ANA_DESC = ("On-shell IC (field_spin = bh_spin): the analytic stationary "
            "Kerr-Wald\n# state sampled on this level's mesh.  One step, so "
            "ic_aux.h5 carries the\n# discrete-equilibrium residual dD/dt, "
            "dB/dt at the exact solution.")
RELAX_DESC = ("Relaxation test: Schwarzschild Wald IC (field_spin = 0) on the "
              "a = 0.998\n# background, evolved to t = 60 M.  Scored by "
              "Phi_cap(horizon)/Phi_cap(r_ref)\n# against the _ana run at the "
              "same level.")


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    for L, N_r, dt, damp, out_M in LEVELS:
        for kind in ("ana", "relax"):
            for whitney in (False, True):
                is_ana = kind == "ana"
                suffix = "_whitney" if whitney else ""
                name = f"config_conv_L{L}_{kind}{suffix}.toml"
                steps = 1 if is_ana else int(round(T_FINAL / dt))
                out_int = 1 if is_ana else int(round(out_M / dt))
                extra = ""
                if whitney and is_ana and L == 3:
                    extra = "\ndump_whitney_hodge = true"
                text = HEADER.format(
                    L=L, kind=("analytic reference" if is_ana
                               else "relaxation run") +
                              (" (Whitney Hodge)" if whitney else ""),
                    desc=ANA_DESC if is_ana else RELAX_DESC,
                ) + BODY.format(
                    L=L, N_r=N_r, dt=dt, bh_spin=BH_SPIN,
                    field_spin=BH_SPIN if is_ana else 0.0,
                    max_steps=steps, damping_length=damp,
                    out_interval=out_int,
                    output_dir=f"Data_conv_L{L}_{kind}{suffix}",
                    use_whitney="true" if whitney else "false",
                    extra=extra,
                )
                with open(os.path.join(here, name), "w") as f:
                    f.write(text)
                print(f"wrote {name}  (N_r={N_r}, dt={dt}, steps={steps}, "
                      f"damp_len={damp})")


if __name__ == "__main__":
    main()
