#!/bin/bash

module load gcc/9.3.0
module load cmake
module load cuda/11.0.2
module load openmpi/4.0.4
module load hdf5
#module load hdf5_perf/1.10.6.gcc

#export PAMI_ENABLE_STRIPING=1
#export PAMI_IBV_ADAPTER_AFFINITY=1
#export PAMI_IBV_DEVICE_NAME="mlx5_0:1,mlx5_3:1"
#export PAMI_IBV_DEVICE_NAME_1="mlx5_3:1,mlx5_0:1"
