#!/bin/bash

module load PrgEnv-cray/8.5.0
module load rocm/6.2.4
module load cray-hdf5-parallel
module load DefApps
module load cmake/3.30.5
module load craype-accel-amd-gfx90a
module load craype-x86-trento


export MPICH_GPU_SUPPORT_ENABLED=1
export LD_LIBRARY_PATH=${CRAY_LD_LIBRARY_PATH}:${LD_LIBRARY_PATH}