#!/bin/bash

module load DefApps-2023
module load cmake/3.27.7
module load cuda/11.0.3
module load gcc/9.3.0
module load boost/1.76.0-cxx17
module load spectrum-mpi/10.4.0.3-20210112
module load hdf5/1.10.7
#module load hdf5_perf/1.10.6.gcc

#export PAMI_ENABLE_STRIPING=1
#export PAMI_IBV_ADAPTER_AFFINITY=1
#export PAMI_IBV_DEVICE_NAME="mlx5_0:1,mlx5_3:1"
#export PAMI_IBV_DEVICE_NAME_1="mlx5_3:1,mlx5_0:1"
