"""A1 study driver: primal Whitney vs vertex-recovery B-gather, particle level.

Needs small meshes generated by problems/prismatic_dipole/bin/vacuum_dipole
(L=2..4, r in [1,2], N_r = 4·2^(L-2); see the roadmap).  Usage:

    python recovery_study.py <mesh_dir_pattern> <out_dir>

where mesh_dir_pattern contains '{L}', e.g. '/path/meshes/L{L}'.
Produces the paper-figure data: gyro-orbit mu conservation in a uniform
field, pitch-angle scattering on dipole drift orbits, and the recovery
conditioning-vs-vertex-class table.
"""

import sys
import time
import numpy as np
import prismatic_recovery as pr


# =========================================================================
# Boris pusher (non-relativistic units: q = m = 1, E = 0 here)
# =========================================================================

def boris_step(x, v, B, dt):
    t = 0.5 * dt * B
    s = 2.0 * t / (1.0 + np.sum(t * t, axis=1, keepdims=True))
    v_prime = v + np.cross(v, t)
    v_new = v + np.cross(v_prime, s)
    x_new = x + dt * v_new
    return x_new, v_new


def run_orbit(x0, v0, field, dt, n_steps, sample_every=10):
    """Integrate an ensemble with Boris; field(x, hints) -> B (N,3).
    Returns times and sampled (x, v, B) history."""
    x, v = x0.copy(), v0.copy()
    hints = np.zeros(len(x0), dtype=int)
    hist = []
    for step in range(n_steps):
        B = field(x, hints)
        if step % sample_every == 0:
            hist.append((step * dt, x.copy(), v.copy(), B.copy()))
        x, v = boris_step(x, v, B, dt)
    return hist


def mu_of(v, B):
    """Magnetic moment mu = v_perp^2 / (2 |B|) per particle."""
    Bn = np.linalg.norm(B, axis=1)
    Bn = np.where(Bn > 0, Bn, np.nan)
    b = B / Bn[:, None]
    v_par = np.sum(v * b, axis=1)
    v_perp2 = np.sum(v * v, axis=1) - v_par**2
    return v_perp2 / (2.0 * Bn)


def pitch_of(v, B):
    Bn = np.linalg.norm(B, axis=1)
    v_par = np.sum(v * B, axis=1) / Bn
    vn = np.linalg.norm(v, axis=1)
    return np.arccos(np.clip(v_par / vn, -1, 1))


# =========================================================================
# Experiment 1: uniform field — recovery is exact, primal scatters
# =========================================================================

def experiment_uniform(mesh, rng, n_ptc=48, n_steps=3000, dt_frac=0.05):
    B0 = np.array([0.0, 0.0, 1.0])
    Bf = pr.flux_cochain(mesh, pr.constant_B(B0), n=6)
    Ee = np.zeros(mesh.N_edges)
    rec = pr.build_recovery(mesh, n=4)
    Bv = pr.vertex_field(mesh, rec, Bf)

    # gyro-orbits well inside the shell, gyro-radius ~ 1/3 of a cell
    r_gyro = 0.06
    r0 = rng.uniform(1.3, 1.7, n_ptc)
    u = rng.normal(size=(n_ptc, 3))
    u /= np.linalg.norm(u, axis=1, keepdims=True)
    x0 = r0[:, None] * u
    # pure perpendicular velocity (uniform B doesn't confine parallel
    # motion, so any v_par walks particles out of the shell)
    v0 = np.cross(B0[None, :], rng.normal(size=(n_ptc, 3)))
    v0 /= np.linalg.norm(v0, axis=1, keepdims=True)
    v0 = r_gyro * v0
    dt = dt_frac * 2 * np.pi  # omega_c = 1

    fields = {
        "exact": lambda x, h: pr.constant_B(B0)(x),
        "primal": lambda x, h: pr.primal_gather(mesh, Ee, Bf, x, h)[1],
        "recovery": lambda x, h: pr.recovery_gather(mesh, Bv, x, h),
    }
    out = {}
    for name, f in fields.items():
        hist = run_orbit(x0, v0, f, dt, n_steps)
        xs = np.array([h[1] for h in hist])
        r_hist = np.linalg.norm(xs, axis=2)
        lost = (r_hist < mesh.radii[0]) | (r_hist > mesh.radii[-1])
        alive = ~np.maximum.accumulate(lost, axis=0)
        ok = alive[-1]
        loss_frac = 1.0 - ok.mean()
        mu = np.array([mu_of(v, B) for _, x, v, B in hist])[:, ok]
        dmu = (mu - mu[0]) / mu[0]
        # guiding-center wander: displacement of the gyro-averaged position
        gc0 = xs[:16, ok].mean(axis=0)
        gc1 = xs[-16:, ok].mean(axis=0)
        wander = np.linalg.norm(gc1 - gc0, axis=1)
        out[name] = {
            "t": np.array([h[0] for h in hist]),
            "loss_frac": loss_frac,
            "dmu_rms": np.sqrt(np.nanmean(dmu[-1] ** 2)),
            "gc_wander": np.median(wander),
        }
        print(
            "  uniform/%-8s: lost %4.1f%%  |  rms dmu/mu %.3e  |  median gc wander %.3e"
            % (name, 100 * loss_frac, out[name]["dmu_rms"], out[name]["gc_wander"])
        )
    return out


# =========================================================================
# Experiment 2: dipole drift orbits — mu conservation across many cells
# =========================================================================

def experiment_dipole(mesh, rng, n_ptc=32, n_steps=6000, dt_frac=0.02):
    Bf = pr.flux_cochain(mesh, pr.dipole_B, n=6)
    Ee = np.zeros(mesh.N_edges)
    rec = pr.build_recovery(mesh, n=4)
    Bv = pr.vertex_field(mesh, rec, Bf)

    # near-equatorial particles, moderate pitch angles: they gyrate,
    # grad-B drift in phi, and bounce shallowly — crossing many prisms.
    r0 = rng.uniform(1.3, 1.6, n_ptc)
    phi0 = rng.uniform(0, 2 * np.pi, n_ptc)
    th0 = np.pi / 2 + rng.uniform(-0.15, 0.15, n_ptc)
    x0 = np.stack(
        [
            r0 * np.sin(th0) * np.cos(phi0),
            r0 * np.sin(th0) * np.sin(phi0),
            r0 * np.cos(th0),
        ],
        axis=1,
    )
    B_at = pr.dipole_B(x0)
    Bn = np.linalg.norm(B_at, axis=1)
    b = B_at / Bn[:, None]
    # v_perp for gyro-radius ~ 0.05 at local B, pitch angle ~ 60 deg
    v_perp = 0.05 * Bn
    e1 = np.cross(b, rng.normal(size=(n_ptc, 3)))
    e1 /= np.linalg.norm(e1, axis=1, keepdims=True)
    v0 = v_perp[:, None] * e1 + (0.6 * v_perp)[:, None] * b
    # timestep on the local gyro-frequency
    dt = dt_frac * 2 * np.pi / Bn.max()

    fields = {
        "exact": lambda x, h: pr.dipole_B(x),
        "primal": lambda x, h: pr.primal_gather(mesh, Ee, Bf, x, h)[1],
        "recovery": lambda x, h: pr.recovery_gather(mesh, Bv, x, h),
    }
    out = {}
    n_samp_avg = 8  # gyro-phase-average window (samples)
    for name, f in fields.items():
        hist = run_orbit(x0, v0, f, dt, n_steps)
        t = np.array([h[0] for h in hist])
        xs = np.array([h[1] for h in hist])  # (n_t, n_ptc, 3)
        mu = np.array([mu_of(v, pr.dipole_B(x)) for _, x, v, B in hist])
        r_hist = np.linalg.norm(xs, axis=2)
        # a particle is lost once it leaves the shell (gather returns 0)
        lost = (r_hist < mesh.radii[0]) | (r_hist > mesh.radii[-1])
        alive = ~np.maximum.accumulate(lost, axis=0)
        loss_frac = 1.0 - alive[-1].mean()
        # gyro-phase-averaged mu at start/end for surviving particles
        ok = alive[-1]
        mu0 = mu[:n_samp_avg, ok].mean(axis=0)
        mu1 = mu[-n_samp_avg:, ok].mean(axis=0)
        dmu = (mu1 - mu0) / mu0
        out[name] = {
            "t": t,
            "loss_frac": loss_frac,
            "dmu_rms": np.sqrt(np.nanmean(dmu**2)),
            "mu_t": np.nanmean(np.abs((mu - mu[:n_samp_avg].mean(axis=0))
                                      / mu[:n_samp_avg].mean(axis=0)) * alive, axis=1),
        }
        print(
            "  dipole/%-8s: lost %4.1f%%  |  phase-avg dmu/mu rms (survivors) %.3e"
            % (name, 100 * loss_frac, out[name]["dmu_rms"])
        )
    return out


# =========================================================================
# Conditioning / fit-quality table (task A1.2)
# =========================================================================

def conditioning_table(mesh):
    rec = pr.build_recovery(mesh, n=4)
    cond = rec["cond"].reshape(mesh.N_r + 1, mesh.N_vert_s)
    rows = []
    for cls, mask in (("valence-6", mesh.valence == 6), ("valence-5", mesh.valence == 5)):
        interior = cond[1:-1, mask]
        boundary = np.concatenate([cond[0, mask], cond[-1, mask]])
        rows.append((cls, np.median(interior), interior.max(), np.median(boundary), boundary.max()))
    print("  %-10s %-24s %-24s" % ("class", "interior med/max", "boundary med/max"))
    for cls, mi, xi, mb, xb in rows:
        print("  %-10s %10.3g / %-10.3g %10.3g / %-10.3g" % (cls, mi, xi, mb, xb))
    return rec


if __name__ == "__main__":
    pattern = sys.argv[1]
    out_dir = sys.argv[2] if len(sys.argv) > 2 else "."
    rng = np.random.default_rng(2026)

    mesh = pr.Mesh(pattern.format(L=3) + "/mesh.h5")
    print("== conditioning (L=3) ==")
    conditioning_table(mesh)
    print("== experiment 1: uniform B (L=3) ==")
    e1 = experiment_uniform(mesh, rng)
    print("== experiment 2: dipole drift orbits (L=3) ==")
    e2 = experiment_dipole(mesh, rng)
    np.savez(
        f"{out_dir}/recovery_study.npz",
        **{f"uniform_{k}_{q}": v for k, d in e1.items() for q, v in d.items()},
        **{f"dipole_{k}_{q}": v for k, d in e2.items() for q, v in d.items()},
    )
    print("saved", f"{out_dir}/recovery_study.npz")
